Repository EnterVPL/FoxSymulator, pull requests merged in 2021-01, with the labels that each got.

#26 Fix/issues 24 25
  langs/EN/animals.json
  langs/PL/actions.json
  langs/PL/animals.json
Labels: Fix

#27 Fix/issues 22and23 inventory menu
  README.md
  game/Color.dart
  inventory/BagMenu.dart
  inventory/WarehouseMenu.dart
Labels: Fix

#31 print stats in inventory
  game/Game.dart
  inventory/BagMenu.dart
  inventory/WarehouseMenu.dart
Labels: enhancement

#32 add close info
  langs/EN/inventory.json
  langs/PL/inventory.json
Labels: enhancement

#33 Feature/Issue #29
  game/Color.dart
  game/Game.dart
Labels: enhancement

#48 Fix/windows console
  changeFont.bat
  game/Game.dart
  langs/EN/options.json
  langs/PL/options.json
  main.dart
Labels: Fix

#50 Fix/windows console
  .gitignore
  FoxyLauncher.bat
  game/Game.dart
  pubspec.yaml
Labels: Fix

#47 Split animals list from locations list.
  animals/AnimalsList.dart
  locations/LocationList.dart
Labels: enhancement

#54 Feature/issue 35 exp stat
  animals/Fox.dart
  animals/Stats.dart
  langs/EN/items.json
  langs/EN/stats.json
  langs/PL/items.json
  langs/PL/stats.json
Labels: enhancement

#56 Feature/issue 37 leveling
  .gitignore
  animals/AnimalsList.dart
  animals/Fight.dart
  animals/Fox.dart
  animals/Friend.dart
  game/Game.dart
  langs/EN/friend.json
  langs/EN/stats.json
  langs/PL/friend.json
  langs/PL/stats.json
  main.dart
Labels: enhancement

#59 Feature/issue 39 new dropping
  animals/Animals.dart
  animals/AnimalsList.dart
  animals/Fight.dart
  animals/Fox.dart
  game/Color.dart
  game/Game.dart
  inventory/BagMenu.dart
  inventory/Inventory.dart
  inventory/WarehouseMenu.dart
Labels: Fix, enhancement

#60 Fix/issue 55 move benefits
  animals/Fox.dart
  game/Handlers.dart
  inventory/InventoryActions.dart
Labels: Fix, enhancement

#61 Feature/issue 41 change fight
  animals/Animals.dart
  animals/Fox.dart
  langs/EN/animals.json
  langs/PL/animals.json
Labels: enhancement

#62 Add drop exp message to end fight
  animals/Fight.dart
  langs/EN/inventory.json
  langs/PL/inventory.json
Labels: enhancement

#64 Feature/issue 63 remove warehouse
  animals/Animals.dart
  animals/Fox.dart
  game/Game.dart
  game/Handlers.dart
  inventory/Inventory.dart
  inventory/InventoryActions.dart
  inventory/WarehouseMenu.dart
  locations/LocationList.dart
Labels: Task, enhancement

#65 fixed exit from boosting
  animals/Friend.dart
Labels: Fix
